<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ParametricTableValueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->now = Carbon::now();
        DB::table('parametric_table_values')->insert([
            ['id' => 1, 'parametric_table_id' => 1, 'name' => 'Area', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 2, 'parametric_table_id' => 1, 'name' => 'Isla', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 3, 'parametric_table_id' => 1, 'name' => 'Juego', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 4, 'parametric_table_id' => 1, 'name' => 'Casa', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 5, 'parametric_table_id' => 1, 'name' => 'MiniJuego', 'parameter' => 5, 'created_at' => $this->now],
            ['id' => 9, 'parametric_table_id' => 3, 'name' => 'Isla', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 10, 'parametric_table_id' => 3, 'name' => 'Casa', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 11, 'parametric_table_id' => 4, 'name' => 'Abajo de la sala', 'parameter' => 0, 'created_at' => $this->now],
            ['id' => 12, 'parametric_table_id' => 4, 'name' => 'Arriba de la sala', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 13, 'parametric_table_id' => 4, 'name' => 'Intermedio de la sala', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 14, 'parametric_table_id' => 4, 'name' => 'Multiple nivel', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 15, 'parametric_table_id' => 5, 'name' => 'UNICO', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 16, 'parametric_table_id' => 5, 'name' => 'CASI UNICO', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 17, 'parametric_table_id' => 5, 'name' => 'MUY RARE', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 18, 'parametric_table_id' => 5, 'name' => 'RARE', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 19, 'parametric_table_id' => 5, 'name' => 'NORMAL', 'parameter' => 0, 'created_at' => $this->now],
            ['id' => 20, 'parametric_table_id' => 6, 'name' => 'Objeto Item', 'parameter' => 0, 'created_at' => $this->now],
            ['id' => 21, 'parametric_table_id' => 6, 'name' => 'Objeto para un escenario', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 22, 'parametric_table_id' => 7, 'name' => 'Objeto pocion', 'parameter' => 28, 'created_at' => $this->now],
            ['id' => 23, 'parametric_table_id' => 7, 'name' => 'Objeto normal', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 24, 'parametric_table_id' => 7, 'name' => 'Objeto volador', 'parameter' => 10, 'created_at' => $this->now],
            ['id' => 25, 'parametric_table_id' => 7, 'name' => 'Objeto hablador', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 26, 'parametric_table_id' => 7, 'name' => 'Objeto clickable', 'parameter' => 36, 'created_at' => $this->now],
            ['id' => 27, 'parametric_table_id' => 8, 'name' => 'Apricion normal', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 28, 'parametric_table_id' => 8, 'name' => 'Apricion desde cielo', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 29, 'parametric_table_id' => 8, 'name' => 'Apricion desvanecida', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 30, 'parametric_table_id' => 9, 'name' => 'Posicionarse encima', 'parameter' => 0, 'created_at' => $this->now],
            ['id' => 31, 'parametric_table_id' => 9, 'name' => 'Hacer click encima', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 32, 'parametric_table_id' => 10, 'name' => 'Nerd', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 33, 'parametric_table_id' => 10, 'name' => 'Vieja', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 34, 'parametric_table_id' => 10, 'name' => 'Rasta', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 35, 'parametric_table_id' => 10, 'name' => 'Viejo', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 36, 'parametric_table_id' => 10, 'name' => 'India', 'parameter' => 5, 'created_at' => $this->now],
            ['id' => 37, 'parametric_table_id' => 10, 'name' => 'Mafioso', 'parameter' => 6, 'created_at' => $this->now],
            ['id' => 38, 'parametric_table_id' => 10, 'name' => 'Zeta', 'parameter' => 7, 'created_at' => $this->now],
            ['id' => 39, 'parametric_table_id' => 10, 'name' => 'Gata', 'parameter' => 8, 'created_at' => $this->now],
            ['id' => 40, 'parametric_table_id' => 10, 'name' => 'Boomer', 'parameter' => 9, 'created_at' => $this->now],
            ['id' => 41, 'parametric_table_id' => 10, 'name' => 'DJ', 'parameter' => 10, 'created_at' => $this->now],
            ['id' => 42, 'parametric_table_id' => 10, 'name' => 'Bruja', 'parameter' => 11, 'created_at' => $this->now],
            ['id' => 43, 'parametric_table_id' => 10, 'name' => 'Ninja', 'parameter' => 12, 'created_at' => $this->now],
            ['id' => 44, 'parametric_table_id' => 10, 'name' => 'Espectro', 'parameter' => 13, 'created_at' => $this->now],
            ['id' => 45, 'parametric_table_id' => 10, 'name' => 'Fantasma', 'parameter' => 14, 'created_at' => $this->now],
            ['id' => 46, 'parametric_table_id' => 10, 'name' => 'Zombi', 'parameter' => 15, 'created_at' => $this->now],
            ['id' => 47, 'parametric_table_id' => 10, 'name' => 'Lobo', 'parameter' => 16, 'created_at' => $this->now],
            ['id' => 48, 'parametric_table_id' => 10, 'name' => 'Esqueleto', 'parameter' => 17, 'created_at' => $this->now],
            ['id' => 49, 'parametric_table_id' => 11, 'name' => 'Crear objetos', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 50, 'parametric_table_id' => 11, 'name' => 'Informativo', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 51, 'parametric_table_id' => 11, 'name' => 'Canjear codigos', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 52, 'parametric_table_id' => 11, 'name' => 'Interactivo', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 53, 'parametric_table_id' => 11, 'name' => 'MiniJuego', 'parameter' => 5, 'created_at' => $this->now],
            ['id' => 54, 'parametric_table_id' => 12, 'name' => 'Sin cartel', 'parameter' => 0, 'created_at' => $this->now],
            ['id' => 55, 'parametric_table_id' => 12, 'name' => 'Carte Marron', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 56, 'parametric_table_id' => 12, 'name' => 'Cartel Morado', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 57, 'parametric_table_id' => 12, 'name' => 'Cartel MiniJuego', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 58, 'parametric_table_id' => 12, 'name' => 'Carte Rojo', 'parameter' => 6, 'created_at' => $this->now],
            ['id' => 59, 'parametric_table_id' => 13, 'name' => 'Objetos Decorativos', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 60, 'parametric_table_id' => 13, 'name' => 'Set Bosque', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 61, 'parametric_table_id' => 13, 'name' => 'Mascotas y cosas parecidas', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 62, 'parametric_table_id' => 13, 'name' => 'Set Miedo', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 63, 'parametric_table_id' => 13, 'name' => 'Set Indio', 'parameter' => 5, 'created_at' => $this->now],
            ['id' => 64, 'parametric_table_id' => 13, 'name' => 'Set Hielo', 'parameter' => 6, 'created_at' => $this->now],
            ['id' => 65, 'parametric_table_id' => 13, 'name' => 'San Valentin', 'parameter' => 7, 'created_at' => $this->now],
            ['id' => 66, 'parametric_table_id' => 13, 'name' => 'Regalos', 'parameter' => 8, 'created_at' => $this->now],
            ['id' => 67, 'parametric_table_id' => 13, 'name' => 'Set Alien', 'parameter' => 9, 'created_at' => $this->now],
            ['id' => 68, 'parametric_table_id' => 13, 'name' => 'Set Pirata', 'parameter' => 11, 'created_at' => $this->now],
            ['id' => 69, 'parametric_table_id' => 13, 'name' => 'Set Oriental', 'parameter' => 13, 'created_at' => $this->now],
            ['id' => 70, 'parametric_table_id' => 13, 'name' => 'Set Magia', 'parameter' => 14, 'created_at' => $this->now],
            ['id' => 71, 'parametric_table_id' => 13, 'name' => 'Set Pascuas', 'parameter' => 15, 'created_at' => $this->now],
            ['id' => 72, 'parametric_table_id' => 13, 'name' => 'Para tu Casita', 'parameter' => 16, 'created_at' => $this->now],
            ['id' => 73, 'parametric_table_id' => 13, 'name' => 'Novedades', 'parameter' => 17, 'created_at' => $this->now],
            ['id' => 74, 'parametric_table_id' => 13, 'name' => 'Plantas', 'parameter' => 19, 'created_at' => $this->now],
            ['id' => 75, 'parametric_table_id' => 13, 'name' => 'Set Navidad', 'parameter' => 20, 'created_at' => $this->now],
            ['id' => 76, 'parametric_table_id' => 13, 'name' => 'BBox', 'parameter' => 21, 'created_at' => $this->now],
            ['id' => 77, 'parametric_table_id' => 13, 'name' => 'Efectos', 'parameter' => 22, 'created_at' => $this->now],
            ['id' => 78, 'parametric_table_id' => 13, 'name' => 'Deportes', 'parameter' => 23, 'created_at' => $this->now],
            ['id' => 79, 'parametric_table_id' => 14, 'name' => 'Estrella', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 80, 'parametric_table_id' => 14, 'name' => 'Corazon', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 81, 'parametric_table_id' => 14, 'name' => 'Flor', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 82, 'parametric_table_id' => 14, 'name' => 'Calavera', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 83, 'parametric_table_id' => 15, 'name' => 'Pocion gigante', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 84, 'parametric_table_id' => 15, 'name' => 'Pocion diminuto', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 85, 'parametric_table_id' => 15, 'name' => 'Pocion murcielagos', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 86, 'parametric_table_id' => 15, 'name' => 'Pocion mudo', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 87, 'parametric_table_id' => 15, 'name' => 'Pocion trabalenguas', 'parameter' => 5, 'created_at' => $this->now],
            ['id' => 88, 'parametric_table_id' => 15, 'name' => 'Pocion texto invertido', 'parameter' => 6, 'created_at' => $this->now],
            ['id' => 89, 'parametric_table_id' => 15, 'name' => 'Pocion invicible', 'parameter' => 7, 'created_at' => $this->now],
            ['id' => 90, 'parametric_table_id' => 15, 'name' => 'Pocion teleporte', 'parameter' => 8, 'created_at' => $this->now],
            ['id' => 91, 'parametric_table_id' => 15, 'name' => 'Pocion rayo', 'parameter' => 9, 'created_at' => $this->now],
            ['id' => 92, 'parametric_table_id' => 15, 'name' => 'Pocion rana', 'parameter' => 10, 'created_at' => $this->now],
            ['id' => 93, 'parametric_table_id' => 15, 'name' => 'Pocion espectro', 'parameter' => 11, 'created_at' => $this->now],
            ['id' => 94, 'parametric_table_id' => 15, 'name' => 'Pocion fantasma', 'parameter' => 12, 'created_at' => $this->now],
            ['id' => 95, 'parametric_table_id' => 15, 'name' => 'Pocion acido', 'parameter' => 13, 'created_at' => $this->now],
            ['id' => 96, 'parametric_table_id' => 15, 'name' => 'Pocion apestoso', 'parameter' => 14, 'created_at' => $this->now],
            ['id' => 97, 'parametric_table_id' => 15, 'name' => 'Pocion teleporte maestro', 'parameter' => 15, 'created_at' => $this->now],
            ['id' => 98, 'parametric_table_id' => 15, 'name' => 'Regalo confeti', 'parameter' => 16, 'created_at' => $this->now],
            ['id' => 99, 'parametric_table_id' => 15, 'name' => 'Regalo ariola', 'parameter' => 17, 'created_at' => $this->now],
            ['id' => 100, 'parametric_table_id' => 15, 'name' => 'Regalo helicoptero', 'parameter' => 18, 'created_at' => $this->now],
            ['id' => 101, 'parametric_table_id' => 15, 'name' => 'Regalo lazer', 'parameter' => 19, 'created_at' => $this->now],
            ['id' => 102, 'parametric_table_id' => 15, 'name' => 'Regalo cohete', 'parameter' => 21, 'created_at' => $this->now],
            ['id' => 103, 'parametric_table_id' => 15, 'name' => 'Regalo muñeco de nieve', 'parameter' => 22, 'created_at' => $this->now],
            ['id' => 104, 'parametric_table_id' => 15, 'name' => 'Regalo tanque', 'parameter' => 23, 'created_at' => $this->now],
            ['id' => 105, 'parametric_table_id' => 15, 'name' => 'Efecto rozas', 'parameter' => 25, 'created_at' => $this->now],
            ['id' => 106, 'parametric_table_id' => 15, 'name' => 'Efecto arcoiris', 'parameter' => 26, 'created_at' => $this->now],
            ['id' => 107, 'parametric_table_id' => 15, 'name' => 'Efecto enamorado', 'parameter' => 27, 'created_at' => $this->now],
            ['id' => 108, 'parametric_table_id' => 15, 'name' => 'Efecto cupido destructor', 'parameter' => 28, 'created_at' => $this->now],
            ['id' => 109, 'parametric_table_id' => 15, 'name' => 'Efecto pajarito cagon', 'parameter' => 29, 'created_at' => $this->now],
            ['id' => 110, 'parametric_table_id' => 15, 'name' => 'Efecto pajarito mensajero', 'parameter' => 30, 'created_at' => $this->now],
            ['id' => 111, 'parametric_table_id' => 15, 'name' => 'Efecto beso', 'parameter' => 31, 'created_at' => $this->now],
            ['id' => 112, 'parametric_table_id' => 15, 'name' => 'Efecto alien 1', 'parameter' => 42, 'created_at' => $this->now],
            ['id' => 113, 'parametric_table_id' => 15, 'name' => 'Efecto alien 2', 'parameter' => 43, 'created_at' => $this->now],
            ['id' => 114, 'parametric_table_id' => 15, 'name' => 'Efecto alien 3', 'parameter' => 44, 'created_at' => $this->now],
            ['id' => 115, 'parametric_table_id' => 15, 'name' => 'Efecto alien 4', 'parameter' => 45, 'created_at' => $this->now],
            ['id' => 116, 'parametric_table_id' => 15, 'name' => 'Efecto alien 5', 'parameter' => 46, 'created_at' => $this->now],
            ['id' => 117, 'parametric_table_id' => 15, 'name' => 'Efecto alien 6', 'parameter' => 47, 'created_at' => $this->now],
            ['id' => 118, 'parametric_table_id' => 16, 'name' => 'Ring', 'parameter' => 0, 'created_at' => $this->now],
            ['id' => 119, 'parametric_table_id' => 16, 'name' => 'Sendero Oculto', 'parameter' => 0, 'created_at' => $this->now],
            ['id' => 120, 'parametric_table_id' => 16, 'name' => 'Cocos Locos', 'parameter' => 0, 'created_at' => $this->now],
            ['id' => 121, 'parametric_table_id' => 16, 'name' => 'Camino Ninja', 'parameter' => 0, 'created_at' => $this->now],
            ['id' => 122, 'parametric_table_id' => 17, 'name' => 'Isla perdida', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 123, 'parametric_table_id' => 17, 'name' => 'Isla volcan', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 124, 'parametric_table_id' => 17, 'name' => 'Isla hielo', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 125, 'parametric_table_id' => 17, 'name' => 'Isla desierto', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 126, 'parametric_table_id' => 17, 'name' => 'Isla de terror', 'parameter' => 5, 'created_at' => $this->now],
            ['id' => 127, 'parametric_table_id' => 18, 'name' => 'Privado', 'parameter' => 0, 'created_at' => $this->now],
            ['id' => 128, 'parametric_table_id' => 18, 'name' => 'Publico', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 129, 'parametric_table_id' => 18, 'name' => 'MGame', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 130, 'parametric_table_id' => 19, 'name' => 'Circulo que parpadea', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 131, 'parametric_table_id' => 19, 'name' => 'Flecha normal arriba', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 132, 'parametric_table_id' => 19, 'name' => 'Flecha normal derecha', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 133, 'parametric_table_id' => 19, 'name' => 'Flecha normal abajo', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 134, 'parametric_table_id' => 19, 'name' => 'Flecha normal esquerda', 'parameter' => 5, 'created_at' => $this->now],
            ['id' => 135, 'parametric_table_id' => 19, 'name' => 'Flecha clara arriba', 'parameter' => 6, 'created_at' => $this->now],
            ['id' => 136, 'parametric_table_id' => 19, 'name' => 'Flecha clara derecha', 'parameter' => 7, 'created_at' => $this->now],
            ['id' => 137, 'parametric_table_id' => 19, 'name' => 'Flecha clara abajo', 'parameter' => 8, 'created_at' => $this->now],
            ['id' => 138, 'parametric_table_id' => 19, 'name' => 'Flecha clara esquerda', 'parameter' => 9, 'created_at' => $this->now],
            ['id' => 139, 'parametric_table_id' => 19, 'name' => 'Flecha oscura arriba', 'parameter' => 10, 'created_at' => $this->now],
            ['id' => 140, 'parametric_table_id' => 19, 'name' => 'Flecha oscura derecha', 'parameter' => 11, 'created_at' => $this->now],
            ['id' => 141, 'parametric_table_id' => 19, 'name' => 'Flecha oscura abajo', 'parameter' => 12, 'created_at' => $this->now],
            ['id' => 142, 'parametric_table_id' => 19, 'name' => 'Flecha oscura esquerda', 'parameter' => 13, 'created_at' => $this->now],
            ['id' => 143, 'parametric_table_id' => 19, 'name' => 'Flecha diagonal esquerda - arriba', 'parameter' => 14, 'created_at' => $this->now],
            ['id' => 144, 'parametric_table_id' => 19, 'name' => 'Flecha diagonal derecha - arriba', 'parameter' => 15, 'created_at' => $this->now],
            ['id' => 145, 'parametric_table_id' => 19, 'name' => 'Flecha diagonal derecha - abajo', 'parameter' => 16, 'created_at' => $this->now],
            ['id' => 146, 'parametric_table_id' => 19, 'name' => 'Flecha diagonal esquerda - abajo', 'parameter' => 17, 'created_at' => $this->now],
            ['id' => 147, 'parametric_table_id' => 20, 'name' => 'Abajo', 'parameter' => 4, 'created_at' => $this->now],
            ['id' => 148, 'parametric_table_id' => 20, 'name' => 'Derecha', 'parameter' => 1, 'created_at' => $this->now],
            ['id' => 149, 'parametric_table_id' => 20, 'name' => 'Esquerda', 'parameter' => 2, 'created_at' => $this->now],
            ['id' => 150, 'parametric_table_id' => 20, 'name' => 'Arriba', 'parameter' => 3, 'created_at' => $this->now],
            ['id' => 151, 'parametric_table_id' => 20, 'name' => 'Diagonal esquerda - arriba', 'parameter' => 6, 'created_at' => $this->now],
            ['id' => 152, 'parametric_table_id' => 20, 'name' => 'Diagonal derecha - arriba', 'parameter' => 5, 'created_at' => $this->now],
            ['id' => 153, 'parametric_table_id' => 20, 'name' => 'Diagonal esquerda - abajo', 'parameter' => 8, 'created_at' => $this->now],
            ['id' => 154, 'parametric_table_id' => 20, 'name' => 'Diagonal derecha - abajo', 'parameter' => 7, 'created_at' => $this->now],
        ]);
    }
}
